(function() {var implementors = {
"ascii":[["impl Ord for <a class=\"enum\" href=\"ascii/enum.AsciiChar.html\" title=\"enum ascii::AsciiChar\">AsciiChar</a>"],["impl Ord for <a class=\"struct\" href=\"ascii/struct.AsciiStr.html\" title=\"struct ascii::AsciiStr\">AsciiStr</a>"],["impl Ord for <a class=\"struct\" href=\"ascii/struct.AsciiString.html\" title=\"struct ascii::AsciiString\">AsciiString</a>"]],
"bytes":[["impl Ord for <a class=\"struct\" href=\"bytes/struct.Bytes.html\" title=\"struct bytes::Bytes\">Bytes</a>"],["impl Ord for <a class=\"struct\" href=\"bytes/struct.BytesMut.html\" title=\"struct bytes::BytesMut\">BytesMut</a>"]],
"crossbeam_epoch":[["impl&lt;T:&nbsp;?Sized + <a class=\"trait\" href=\"crossbeam_epoch/trait.Pointable.html\" title=\"trait crossbeam_epoch::Pointable\">Pointable</a>&gt; Ord for <a class=\"struct\" href=\"crossbeam_epoch/struct.Shared.html\" title=\"struct crossbeam_epoch::Shared\">Shared</a>&lt;'_, T&gt;"]],
"either":[["impl&lt;L:&nbsp;Ord, R:&nbsp;Ord&gt; Ord for <a class=\"enum\" href=\"either/enum.Either.html\" title=\"enum either::Either\">Either</a>&lt;L, R&gt;"]],
"hermit_abi":[["impl Ord for <a class=\"struct\" href=\"hermit_abi/struct.Priority.html\" title=\"struct hermit_abi::Priority\">Priority</a>"],["impl Ord for <a class=\"struct\" href=\"hermit_abi/struct.Handle.html\" title=\"struct hermit_abi::Handle\">Handle</a>"],["impl Ord for <a class=\"enum\" href=\"hermit_abi/enum.Version.html\" title=\"enum hermit_abi::Version\">Version</a>"],["impl Ord for <a class=\"struct\" href=\"hermit_abi/struct.Ipv4Address.html\" title=\"struct hermit_abi::Ipv4Address\">Ipv4Address</a>"],["impl Ord for <a class=\"struct\" href=\"hermit_abi/struct.Ipv6Address.html\" title=\"struct hermit_abi::Ipv6Address\">Ipv6Address</a>"],["impl Ord for <a class=\"enum\" href=\"hermit_abi/enum.IpAddress.html\" title=\"enum hermit_abi::IpAddress\">IpAddress</a>"]],
"httpdate":[["impl Ord for <a class=\"struct\" href=\"httpdate/struct.HttpDate.html\" title=\"struct httpdate::HttpDate\">HttpDate</a>"]],
"log":[["impl Ord for <a class=\"enum\" href=\"log/enum.Level.html\" title=\"enum log::Level\">Level</a>"],["impl Ord for <a class=\"enum\" href=\"log/enum.LevelFilter.html\" title=\"enum log::LevelFilter\">LevelFilter</a>"],["impl&lt;'a&gt; Ord for <a class=\"struct\" href=\"log/struct.Metadata.html\" title=\"struct log::Metadata\">Metadata</a>&lt;'a&gt;"],["impl&lt;'a&gt; Ord for <a class=\"struct\" href=\"log/struct.MetadataBuilder.html\" title=\"struct log::MetadataBuilder\">MetadataBuilder</a>&lt;'a&gt;"]],
"tiny_http":[["impl Ord for <a class=\"struct\" href=\"tiny_http/struct.StatusCode.html\" title=\"struct tiny_http::StatusCode\">StatusCode</a>"],["impl Ord for <a class=\"struct\" href=\"tiny_http/struct.HTTPVersion.html\" title=\"struct tiny_http::HTTPVersion\">HTTPVersion</a>"]],
"vec_map":[["impl&lt;V:&nbsp;Ord&gt; Ord for <a class=\"struct\" href=\"vec_map/struct.VecMap.html\" title=\"struct vec_map::VecMap\">VecMap</a>&lt;V&gt;"]]
};if (window.register_implementors) {window.register_implementors(implementors);} else {window.pending_implementors = implementors;}})()