(function() {var implementors = {
"ansi_term":[["impl Copy for <a class=\"struct\" href=\"ansi_term/struct.Prefix.html\" title=\"struct ansi_term::Prefix\">Prefix</a>"],["impl Copy for <a class=\"struct\" href=\"ansi_term/struct.Infix.html\" title=\"struct ansi_term::Infix\">Infix</a>"],["impl Copy for <a class=\"struct\" href=\"ansi_term/struct.Suffix.html\" title=\"struct ansi_term::Suffix\">Suffix</a>"],["impl Copy for <a class=\"struct\" href=\"ansi_term/struct.Style.html\" title=\"struct ansi_term::Style\">Style</a>"],["impl Copy for <a class=\"enum\" href=\"ansi_term/enum.Colour.html\" title=\"enum ansi_term::Colour\">Colour</a>"]],
"ascii":[["impl Copy for <a class=\"enum\" href=\"ascii/enum.AsciiChar.html\" title=\"enum ascii::AsciiChar\">AsciiChar</a>"],["impl Copy for <a class=\"struct\" href=\"ascii/struct.ToAsciiCharError.html\" title=\"struct ascii::ToAsciiCharError\">ToAsciiCharError</a>"],["impl Copy for <a class=\"struct\" href=\"ascii/struct.AsAsciiStrError.html\" title=\"struct ascii::AsAsciiStrError\">AsAsciiStrError</a>"],["impl&lt;O:&nbsp;Copy&gt; Copy for <a class=\"struct\" href=\"ascii/struct.FromAsciiError.html\" title=\"struct ascii::FromAsciiError\">FromAsciiError</a>&lt;O&gt;"]],
"atty":[["impl Copy for <a class=\"enum\" href=\"atty/enum.Stream.html\" title=\"enum atty::Stream\">Stream</a>"]],
"clap":[["impl Copy for <a class=\"enum\" href=\"clap/enum.AppSettings.html\" title=\"enum clap::AppSettings\">AppSettings</a>"],["impl Copy for <a class=\"enum\" href=\"clap/enum.ArgSettings.html\" title=\"enum clap::ArgSettings\">ArgSettings</a>"],["impl Copy for <a class=\"enum\" href=\"clap/enum.Shell.html\" title=\"enum clap::Shell\">Shell</a>"],["impl Copy for <a class=\"enum\" href=\"clap/enum.ErrorKind.html\" title=\"enum clap::ErrorKind\">ErrorKind</a>"]],
"core_affinity":[["impl Copy for <a class=\"struct\" href=\"core_affinity/struct.CoreId.html\" title=\"struct core_affinity::CoreId\">CoreId</a>"]],
"crossbeam_channel":[["impl&lt;T:&nbsp;Copy&gt; Copy for <a class=\"struct\" href=\"crossbeam_channel/struct.SendError.html\" title=\"struct crossbeam_channel::SendError\">SendError</a>&lt;T&gt;"],["impl&lt;T:&nbsp;Copy&gt; Copy for <a class=\"enum\" href=\"crossbeam_channel/enum.TrySendError.html\" title=\"enum crossbeam_channel::TrySendError\">TrySendError</a>&lt;T&gt;"],["impl&lt;T:&nbsp;Copy&gt; Copy for <a class=\"enum\" href=\"crossbeam_channel/enum.SendTimeoutError.html\" title=\"enum crossbeam_channel::SendTimeoutError\">SendTimeoutError</a>&lt;T&gt;"],["impl Copy for <a class=\"struct\" href=\"crossbeam_channel/struct.RecvError.html\" title=\"struct crossbeam_channel::RecvError\">RecvError</a>"],["impl Copy for <a class=\"enum\" href=\"crossbeam_channel/enum.TryRecvError.html\" title=\"enum crossbeam_channel::TryRecvError\">TryRecvError</a>"],["impl Copy for <a class=\"enum\" href=\"crossbeam_channel/enum.RecvTimeoutError.html\" title=\"enum crossbeam_channel::RecvTimeoutError\">RecvTimeoutError</a>"],["impl Copy for <a class=\"struct\" href=\"crossbeam_channel/struct.TrySelectError.html\" title=\"struct crossbeam_channel::TrySelectError\">TrySelectError</a>"],["impl Copy for <a class=\"struct\" href=\"crossbeam_channel/struct.SelectTimeoutError.html\" title=\"struct crossbeam_channel::SelectTimeoutError\">SelectTimeoutError</a>"],["impl Copy for <a class=\"struct\" href=\"crossbeam_channel/struct.TryReadyError.html\" title=\"struct crossbeam_channel::TryReadyError\">TryReadyError</a>"],["impl Copy for <a class=\"struct\" href=\"crossbeam_channel/struct.ReadyTimeoutError.html\" title=\"struct crossbeam_channel::ReadyTimeoutError\">ReadyTimeoutError</a>"]],
"crossbeam_deque":[["impl&lt;T:&nbsp;Copy&gt; Copy for <a class=\"enum\" href=\"crossbeam_deque/enum.Steal.html\" title=\"enum crossbeam_deque::Steal\">Steal</a>&lt;T&gt;"]],
"crossbeam_epoch":[["impl&lt;T:&nbsp;?Sized + <a class=\"trait\" href=\"crossbeam_epoch/trait.Pointable.html\" title=\"trait crossbeam_epoch::Pointable\">Pointable</a>&gt; Copy for <a class=\"struct\" href=\"crossbeam_epoch/struct.Shared.html\" title=\"struct crossbeam_epoch::Shared\">Shared</a>&lt;'_, T&gt;"]],
"crossbeam_utils":[["impl&lt;T:&nbsp;Copy&gt; Copy for <a class=\"struct\" href=\"crossbeam_utils/struct.CachePadded.html\" title=\"struct crossbeam_utils::CachePadded\">CachePadded</a>&lt;T&gt;"]],
"either":[["impl&lt;L:&nbsp;Copy, R:&nbsp;Copy&gt; Copy for <a class=\"enum\" href=\"either/enum.Either.html\" title=\"enum either::Either\">Either</a>&lt;L, R&gt;"]],
"hermit_abi":[["impl Copy for <a class=\"struct\" href=\"hermit_abi/struct.Priority.html\" title=\"struct hermit_abi::Priority\">Priority</a>"],["impl Copy for <a class=\"struct\" href=\"hermit_abi/struct.Handle.html\" title=\"struct hermit_abi::Handle\">Handle</a>"],["impl Copy for <a class=\"struct\" href=\"hermit_abi/struct.timespec.html\" title=\"struct hermit_abi::timespec\">timespec</a>"],["impl Copy for <a class=\"enum\" href=\"hermit_abi/enum.Version.html\" title=\"enum hermit_abi::Version\">Version</a>"],["impl Copy for <a class=\"struct\" href=\"hermit_abi/struct.Ipv4Address.html\" title=\"struct hermit_abi::Ipv4Address\">Ipv4Address</a>"],["impl Copy for <a class=\"struct\" href=\"hermit_abi/struct.Ipv6Address.html\" title=\"struct hermit_abi::Ipv6Address\">Ipv6Address</a>"],["impl Copy for <a class=\"enum\" href=\"hermit_abi/enum.IpAddress.html\" title=\"enum hermit_abi::IpAddress\">IpAddress</a>"],["impl Copy for <a class=\"struct\" href=\"hermit_abi/struct.in_addr.html\" title=\"struct hermit_abi::in_addr\">in_addr</a>"],["impl Copy for <a class=\"struct\" href=\"hermit_abi/struct.in6_addr.html\" title=\"struct hermit_abi::in6_addr\">in6_addr</a>"],["impl Copy for <a class=\"struct\" href=\"hermit_abi/struct.sockaddr.html\" title=\"struct hermit_abi::sockaddr\">sockaddr</a>"],["impl Copy for <a class=\"struct\" href=\"hermit_abi/struct.sockaddr_in.html\" title=\"struct hermit_abi::sockaddr_in\">sockaddr_in</a>"],["impl Copy for <a class=\"struct\" href=\"hermit_abi/struct.sockaddr_in6.html\" title=\"struct hermit_abi::sockaddr_in6\">sockaddr_in6</a>"],["impl Copy for <a class=\"struct\" href=\"hermit_abi/struct.addrinfo.html\" title=\"struct hermit_abi::addrinfo\">addrinfo</a>"],["impl Copy for <a class=\"struct\" href=\"hermit_abi/struct.sockaddr_storage.html\" title=\"struct hermit_abi::sockaddr_storage\">sockaddr_storage</a>"],["impl Copy for <a class=\"struct\" href=\"hermit_abi/struct.ip_mreq.html\" title=\"struct hermit_abi::ip_mreq\">ip_mreq</a>"],["impl Copy for <a class=\"struct\" href=\"hermit_abi/struct.ipv6_mreq.html\" title=\"struct hermit_abi::ipv6_mreq\">ipv6_mreq</a>"],["impl Copy for <a class=\"struct\" href=\"hermit_abi/struct.linger.html\" title=\"struct hermit_abi::linger\">linger</a>"],["impl Copy for <a class=\"struct\" href=\"hermit_abi/struct.timeval.html\" title=\"struct hermit_abi::timeval\">timeval</a>"],["impl Copy for <a class=\"struct\" href=\"hermit_abi/struct.pollfd.html\" title=\"struct hermit_abi::pollfd\">pollfd</a>"]],
"httpdate":[["impl Copy for <a class=\"struct\" href=\"httpdate/struct.HttpDate.html\" title=\"struct httpdate::HttpDate\">HttpDate</a>"]],
"log":[["impl Copy for <a class=\"enum\" href=\"log/enum.Level.html\" title=\"enum log::Level\">Level</a>"],["impl Copy for <a class=\"enum\" href=\"log/enum.LevelFilter.html\" title=\"enum log::LevelFilter\">LevelFilter</a>"]],
"tiny_http":[["impl Copy for <a class=\"struct\" href=\"tiny_http/struct.StatusCode.html\" title=\"struct tiny_http::StatusCode\">StatusCode</a>"]]
};if (window.register_implementors) {window.register_implementors(implementors);} else {window.pending_implementors = implementors;}})()